services:

  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: jenkins-ubuntu104        # nom qui apparaitra dans le dashboard Tailscale
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true #utili si nickfedor/watchtower est deployé
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - /home/fahim/docker/jenkins/tailscale-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
      - /etc/localtime:/etc/localtime:ro
    environment:
      - "TS_AUTHKEY=<TAILSCALE_AUTH_KEY>"  # Remplacez <TAILSCALE_AUTH_KEY> par votre clé d'authentification Tailscale
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    network_mode: host                 # tailscale a besoin du réseau host pour fonctionner
    dns:
      - 100.100.100.100 # pour que jenkins puisse résoudre les noms de domaine via Tailscale
      - 1.1.1.1

  jenkins:
    image: jenkins/jenkins:2.555.3-lts
    container_name: jenkins
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
    depends_on:
      - tailscale
    network_mode: service:tailscale    # jenkins partage le réseau de tailscale (pattern sidecar)
    user: root                         # nécessaire pour accès au socket docker si besoin plus tard
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=true
    volumes:
      - /home/fahim/docker/jenkins/jenkins-data:/var/jenkins_home
      - /etc/localtime:/etc/localtime:ro